on:
  push:
    tags:
      - 'v*.*.*'

name: Cross-compile

jobs:
  build_release:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [
          linux,
          rpi,
          aarm64
        ]
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/cvm
            asset_name: cvm-x86_64
            target: x86_64-unknown-linux-musl
          - name: rpi
            os: ubuntu-latest
            artifact_name: target/release/cvm
            asset_name: cvm-armv7
            target: armv7-unknown-linux-gnueabihf
          - name: aarm64
            os: ubuntu-latest
            artifact_name: target/release/cvm
            asset_name: cvm-aarch64
            target: aarch64-unknown-none
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build Release
        run: cargo build --release --locked

      - name: Build Debug
        run: cargo build

      - name: Tar release files
        run: tar -czf ${{ matrix.asset_name }}.tar.gz --directory=target/release/ cvm

      - name: Tar debug files
        run: tar -czf ${{ matrix.asset_name }}-debug.tar.gz --directory=target/debug/ cvm

      - name: Upload release binaries to release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}.tar.gz
          path: ${{ matrix.asset_name }}.tar.gz

      - name: Upload debug binaries to release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}-debug.tar.gz
          path: ${{ matrix.asset_name }}-debug.tar.gz

      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN_DEPLOY }}
          file: ${{ matrix.asset_name }}.tar.gz
          asset_name: ${{ matrix.asset_name }}.tar.gz
          tag: ${{ github.ref }}

      - name: Create Release with debug
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN_DEPLOY }}
          file: ${{ matrix.asset_name }}-debug.tar.gz
          asset_name: ${{ matrix.asset_name }}-debug.tar.gz
          tag: ${{ github.ref }}