on:
  push:
    tags:
      - 'v*.*.*'

name: Cross-compile

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [
          linux,
          rpi,
          aarm64
        ]
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/cvm
            asset_name: cvm-x86-64-unknown-linux-gnu
            target: x86_64-unknown-linux-gnu
          - name: rpi
            os: ubuntu-latest
            artifact_name: target/release/cvm
            asset_name: cvm-armv7-unknown-linux-gnueabihf
            target: armv7-unknown-linux-gnueabihf
          - name:aarm64
            os: ubuntu-latest
            artifact_name: target/release/cvm
            asset_name: cvm-aarch64-unknown-none
            target: aarch64-unknown-none
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release --locked

      - name: Tar files
        run: tar -czf ${{ matrix.asset_name }}.tar.gz --directory=target/release/ cvm

      - name: Upload binaries to release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}.tar.gz
          path: ${{ matrix.asset_name }}.tar.gz

      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN_DEPLOY }}
          file: ${{ matrix.asset_name }}.tar.gz
          asset_name: ${{ matrix.asset_name }}.tar.gz
          tag: ${{ github.ref }}
